/**
 ******************************************************************************
 * @file      syscalls.c
 * @author    Auto-generated by STM32CubeIDE
 * @brief     STM32CubeIDE Minimal System calls file
 *
 *            For more information about which c-functions
 *            need which of these lowlevel functions
 *            please consult the Newlib libc-manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2020-2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "bsp-interface/di/console.h"

extern "C"
{

#include <errno.h>
#include <stdlib.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <sys/times.h>
#include <unistd.h>

	int _getpid(void)
	{
		return 1;
	}

	int _kill(int pid, int sig)
	{
		errno = EINVAL;
		return -1;
	}

	void _exit(int status)
	{
		_kill(status, -1);
		while (1)
		{
			/* Make sure we hang here */
		}
	}

	int _read(int file, char *ptr, int len)
	{
		return EIO;
	}

	/// @brief stdio 底层会调用本函数。
	///
	/// @param file 文件描述符
	/// @note 对于标准输出，file = 1，对于错误输出，file = 2。
	///
	/// @param ptr
	/// @param len
	/// @return
	int _write(int file, char *ptr, int len)
	{
		try
		{
			bsp::di::Console().Write(ptr, len);
			return len;
		}
		catch (...)
		{
			return EIO;
		}
	}

	int _close(int file)
	{
		return -1;
	}

	int _fstat(int file, struct stat *st)
	{
		st->st_mode = S_IFCHR;
		return 0;
	}

	int _isatty(int file)
	{
		return 0;
	}

	int _lseek(int file, int ptr, int dir)
	{
		return 0;
	}

	int _open(char *path, int flags, ...)
	{
		/* Pretend like we always fail */
		return -1;
	}

	int _wait(int *status)
	{
		errno = ECHILD;
		return -1;
	}

	int _unlink(char *name)
	{
		errno = ENOENT;
		return -1;
	}

	int _times(struct tms *buf)
	{
		return -1;
	}

	int _stat(char *file, struct stat *st)
	{
		st->st_mode = S_IFCHR;
		return 0;
	}

	int _link(char *old, char *new_value)
	{
		errno = EMLINK;
		return -1;
	}

	int _fork(void)
	{
		errno = EAGAIN;
		return -1;
	}

	int _execve(char *name, char **argv, char **env)
	{
		errno = ENOMEM;
		return -1;
	}

	char *getenv(char const *name)
	{
		return nullptr;
	}

	int fputc(int ch, FILE *f)
	{
		return ch;
	}

	int fputs(char const *str, FILE *f)
	{
		// 成功返回0，可以根据实际需求调整
		return 0;
	}
}
